AllCops:
  Include:
    - '**/Rakefile'
    - '**.gemspec'
    - '**/config.ru'
    - '.simplecov'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Metrics/MethodLength:
  Max: 64
